### PR TITLE
Filled out "Use Operator Overloads Judiciously"

### PR DESCRIPTION
**Pull request by daniel-kun**
Added some thoughts and some high ranked (and good) links to web
resources

### CODE REVIEW

**Comment by lefticus** [comment]
My only comment is that I'm not 100% sure the conversion operator advice is still valid in the light of the C++11 `explicit` conversion operators. Specifically this comment:

> Do not use conversion operators except `operator bool` for values that clearly have a "true" or "false" state, or "right" or "wrong" so that you can write `if (myValue)` even if myValue is of a custom class.

I'm considering posting this question about conversion operators to twitter to see if we can get someone who knows better than I to comment. What do you think?

**Comment by daniel-kun** [comment]
Ah right, totally forgot about explicit conversion operators. I'm not all too familiar with them, neither. I guess you have to use a static_cast to call them? It's late, I'm too tired to Google. Yup, asking on Twitter might shed light on this topic :-)

(btw, we need a big chapter about resource management and ctors, cctors, move-ctors and operator=)

**Comment by lefticus** [comment]
In the intro I comment that I'm not trying to supplant books like *Effective C++* so I might be reluctant to go very deep into something like resource management beyond that which should live in a standards document. I'll post this question to twitter and see what the internets say about conversion operators anyhow though.

**Comment by lefticus** [comment]
I'm going to go ahead and merge this, then make a quick change for the "avoid implicit conversions" topic we discussed on twitter.

**Pull request merged**
