### PR TITLE
Note that optimization can improve warnings.

### PR DESCRIPTION
**Pull request by ColinH**

### CODE REVIEW

**Comment by lefticus** [comment]
I'm not familiar with warnings that only work (or work better) with optimizations enabled. Can you please update the PR to elaborate on which warnings or give an example?

Thanks!

**Comment by ColinH** [comment]
If you look at https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html you'll find several, for example `-Wnull-dereference`. Are you sure you want such an example in the text?

**Comment by lefticus** [comment]
I would say something like "(Ex: [-Wnull-dereference](https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wnull-dereference-367))"

Keep it very short

**Comment by ColinH** [comment]
Ok :-)

**Pull request merged**
